#!/usr/bin/env bash
# Hook that checks PHP syntax

php_files=$(git status --short | grep -E '^(A|M)' | awk '{ print $2 }' | grep -E '\.php$')
exit_code=0

for file in $php_files; do
  php_out=$(php -l "$file" 2>&1)
  if ! [ $? -eq 0 ]; then
    exit_code=1
    echo "$php_out"
    echo
  fi
done

exit $exit_code
